version: "3.5"

services:
   server:
        image: koush/scrypted
        restart: unless-stopped
        network_mode: host
        environment:
            - SCRYPTED_NVR_VOLUME=/nvr
            # - SCRYPTED_DOCKER_AVAHI=true
        volumes:
            - ${APP_DATA_DIR}/data/video:/nvr
            - ${APP_DATA_DIR}/data/volume:/server/volume
        devices: [
            "/dev/dri:/dev/dri"
            # all usb devices, such as coral tpu
            # "/dev/bus/usb:/dev/bus/usb",
            # coral PCI devices
            # "/dev/apex_0:/dev/apex_0",
            # "/dev/apex_1:/dev/apex_1",
        ]
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
