version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: personal-watch-your-lan_web_1
      APP_PORT: 8840

  web:
    image: aceberg/watchyourlan
    network_mode: "host"        
    restart: on-failure
    stop_grace_period: 1m
    init: true
    environment:
      IFACE: "eth0 wlan0"               # required: 1 or more interface
      DBPATH: "/data/db.sqlite"         # optional, default: /data/db.sqlite
      GUIIP: "0.0.0.0"                  # optional, default: localhost
      GUIPORT: "8840"                   # optional, default: 8840
      TIMEOUT: "120"                    # optional, time in seconds, default: 60
      THEME: "darkly"                   # optional
      IGNOREIP: "no"                    # optional
    volumes:
    - ${APP_DATA_DIR}/data:/data
    - /etc/localtime:/etc/localtime:ro